spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/jhipster;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


eureka:
  client:
    enabled: false

